### ISSUE TITLE
Function decleration registration

### ISSUE THREAD

**Issue by jaynus** [intercept/intercept#10]
@NouberNou 

We talked about the ability to also call the function registration handlers, and inject and register new SQF functions. We need this functionality to properly call back into the C++ realm.

the ability to register

TYPE functionname ARRAY( TYPE,  TYPE, TYPE) would be ideal - with return values. This would allow us to begin registering extended SQF functionality.

**Comment by dedmen** [comment]
https://github.com/dedmen/intercept/commit/fd875534c1f9aab00054bb79a8bc14b97ae2bad9
First draft. Working fine for binary operators with types STRING or ARRAY on profiling build v16 and only if the Module that registered them never unloads. But it's a start.

**Comment by dedmen** [comment]
PR is there now. #123
