### ISSUE TITLE
handgun_items call to engine crashes the game

### ISSUE THREAD

**Issue by jonpas** [intercept/intercept#102]
Simply doing the following without any return value (`void`) or anything else causes a crash (no error):

```
host::functions.invoke_raw_unary(client::__sqf::unary__handgunitems__object__ret__array, unit_);
```

Used in the wrapper: https://github.com/intercept/intercept/blob/master/src/client/intercept/client/sqf/uncategorized.cpp#L10377

**Comment by dedmen** [comment]
https://github.com/intercept/intercept/commit/3704c601f94710ab3103f1ac0b6f701e69dfa222#diff-e601d05fc5e8be313d378ddf06550f59R10377

**Comment by dedmen** [comment]
Works fine in latest develop.
`{silencer="muzzle_snds_acp" laser="" optics="optic_MRD" }`
