### ISSUE TITLE
[Question] How dependent is this on BI's blessing?

### ISSUE THREAD

**Issue by marceldev89** [intercept/intercept#104]
All this is pretty cool and what not but I'm having some issues to actually start building something with it.

The biggest issue that I, and probably many others, at the moment have is how dependent this is on BI's blessing. It would be quite sad to put in an x amount of work and then at some point it's all rendered pointless because BI decides to actively work against it or something a like. Likewise for the effort you guys put in to this.

I get that the project is still in it's early stages but it's probably an important topic.

**Comment by NouberNou** [comment]
We've poked them and made them aware of the project, and so far the only response from them has been interest in its progression. That isn't to say they approve in any official manner, but it seems positive so far.

**Comment by marceldev89** [comment]
That does somewhat seems promising. Thank you. :smile:
