### ISSUE TITLE
Extension reload crashes

### ISSUE THREAD

**Issue by dedmen** [intercept/intercept#113]
Always reproducible with 
```c++
void __cdecl intercept::on_frame() {
    if (!vec) {
        std::vector<std::string> classes{"B_Quadbike_01_F","B_LSV_01_armed_F","B_Boat_Transport_01_F","B_Lifeboat"};
        std::uniform_int_distribution<int> dist(0, classes.size()-1);//Get random classname
        vec = new Vehicle(classes.at(dist(e2)), intercept::sqf::get_pos(sqf::player()) + vector3{ 0,15,0 });
    } else {
        vec->turn();
        if (vec->timeAlive() > 4s) {
            delete vec;
            vec = nullptr;
        }    
    }
}
```
basically spawning a new vehicle every 4 seconds. Runs fine for tens of minutes. But when unloading Extension and then loading it again. It runs for 2 more seconds just fine and then crash in DirectX dll (nvwgf2um.dll)
DirectX is accessing a memory region that doesn't belong to any Module (There never was any allocated memory in there)
Doesn't really seem related to Intercept. But it's still happening

**Comment by jonpas** [comment]
> Doesn't really seem related to Intercept. But it's still happening

Could be Intercept is just exposing abug.

**Comment by dedmen** [comment]
I thought it may be because our self allocated memory will get deallocated on unload.. But the crash is not happening just at unload so thats probably not it.. Have to retest that after armaAlloc is done

**Comment by dedmen** [comment]
Whatever it was it's fixed now.
