### ISSUE TITLE
Use correct Containers in the loader.

### ISSUE THREAD

**Issue by dedmen** [intercept/intercept#115]
Through my Debugger Project I have a couple working implementations for RV Containers. We could use them to massivly simplify the Function loader.
https://github.com/dedmen/ArmaDebugEngine/blob/master/BIDebugEngine/BIDebugEngine/RVContainer.h
https://github.com/dedmen/ArmaDebugEngine/blob/master/BIDebugEngine/BIDebugEngine/RVClasses.h#L335

Also have a function that parses the script functions:
https://github.com/dedmen/ArmaDebugEngine/blob/master/BIDebugEngine/BIDebugEngine/Debugger.cpp#L454

My MapStringToClass container is Read-only but we don't need to create our own script Functions yet anyway.

**Comment by overfl0** [comment]
As you said previously, your code is GPLv3, which prevents it from being incorporated into Intercept, as is.

In case Nou agrees to use those structures, I see a few solutions:
* You push those changes yourself (as the copyright owner)
* You give an explicit consent somewhere about Intercept using this part of your code (might become problematic if someone decides to fork and rename Intercept to some other name in the future)
* The files that would need to be taken from your repository (only those) would be relicensed under the MIT license and all the other files of ArmaDebugEngine would stay GPLv3
* A separate repository could be created to hold those files. That repo would be MIT- or BSD-licensed and both projects would use it as a submodule.

The last two would be preferred as they would allow further changes in the future, without you having to be present each time.
As for relicensing the separate files, I think that you would just need to add a MIT/BSD license header at the start of those files. Then, those files would be MIT-licensed and your own project would actually be a GPL project using MIT files, which is perfectly acceptable from the GPL standpoint.

**Comment by dedmen** [comment]
I am also using parts of Intercept in my Code. Though these parts were written by me for Intercept ^^
I think the first point is a good solution. If we think about the Intercept part of the Code being written by me specially for Intercept. That Intercept part is not a copy of my GPL code. It's a seperate variant written by myself under the MIT license. That should work shouldn't it? That would also not require my consent for changes because it will be Intercept code. And not a Copy of ArmaDebugEngine code.
Most of it is gonna have to be changed anyway because `snake_case`.

**Comment by overfl0** [comment]
`That should work shouldn't it?`
You don't need to employ any loopholes here. If you're the author of the code the license doesn't matter; it's that simple :). You can do anything you want, including relicensing your code, which you do by comitting it to another repo.
The only deviation from this rule is if you're doing paid work and you waive your copyright claims on your contract, but this does not apply here.

`That would also not require my consent for changes because it will be Intercept code.`
That's true but I was talking about the situation where BI guys change the structures again and you, or someone else updates your repo, without updating intercept yourself.

Then, from a formal point of view, it could be problematic for someone else to just take those changes and port them to Intercept, without doing original research.
It would just be much easier to have a common code base to be used by both projects and any change would then need to be applied once.

The naming convention difference is a hindrance here, though...

**Comment by dedmen** [comment]
Yeah. For all the containers and Classes that I may implement in the DebugEngine it would be very benificial to have a common library. Could call it an SDK. Arma Engine SDK.

**Comment by overfl0** [comment]
`We would basically do a publicly available open-source Arma Hack framework.`
I haven't thought of that in that context.

In that case, it may seem more sensible to keep using (that damn ugly) pointer arithmetic. Maybe have those structures shared between a few trusted people and use some kind of internal preprocessor macros that would update the code files with the values of `offsetof()` each time the structures are updated? (manually executed by the committer on his own source code before committing)

Food for thoughts.

Btw. all the required structures are already available in your DebugEngine, aren't they? Will it matter if they are in your headers, in Intercept's or in the headers of a separate common project? These are just `.h` files after all (unless I'm missing something) and I don't really see them being tailored to anything, contrarily to what you're saying.

**Comment by dedmen** [comment]
Like I said. Having these structures inside Intercept/Debug Engine it's a bit closed off. If hackers want to use them they first have to cut them out of the Project and make their own standalone variant.
But If we create an SDK there would already be a standalone variant. If hacker wants it: Copy-paste and done.
Though youre right. I already have most of it in a single header. So it's quite easy to extract it.

**Comment by dedmen** [comment]
Done in  #129
