### ISSUE TITLE
abort() on Arma exit

### ISSUE THREAD

**Issue by overfl0** [intercept/intercept#118]
1. Run Arma 3 with intercept enabled
2. Attach with the debugger (debugging intercept.dll)
3. When the main menu shows up, close Arma

You'll get this in the Output window:
```
Exception thrown at 0x7775C54F in arma3_noreloc.exe: Microsoft C++ exception: std::system_error at memory location 0x02DBF6A0.
Debug Error!

Program: (...)\Steam\steamapps\common\Arma 3\arma3_noreloc.exe

abort() has been called

(Press Retry to debug the application)
The program '[0x22C4] arma3_noreloc.exe' has exited with code 0 (0x0).
```

This does not happen with Intercept disabled.

**Comment by dedmen** [comment]
calltrace?

**Comment by overfl0** [comment]
Unfortunately, I don't know how to provide that. Besides the error message, nothing else happens.
I wouldn't even have noticed anything went wrong if I wasn't paying attention to the Output window.

Also, it should be fairly easy to reproduce that as the only thing you have to do is to attach to Intercept and then close Arma.

**Comment by dedmen** [comment]
Normally at that message you can press retry and it will break into the debugger.
There is a different crash at arma exit present right now. Which I'll fix when i find time. So it's probably not that easy to reproduce this crash without triggering the other one.

**Comment by overfl0** [comment]
Unfortunately, this is a different kind of message to other error messages. It does *not* show any message box - it's just text that appears in the Output window.

There is literally nothing more shown to the user after that happens. The program just stops afterwards.

**Comment by jonpas** [comment]
I can't reproduce that (at least not anymore), with debugger attached or not.

**Comment by dedmen** [comment]
Also can't reproduce. All crashes at Arma exit are caused by myself.
