### ISSUE TITLE
optimise boot.sqf

### ISSUE THREAD

**Issue by shukari** [intercept/intercept#156]
read last comment from killzonekid -> https://community.bistudio.com/wiki/str

for the last line in boost.sqf

**Comment by jonpas** [comment]
Whole file needs to be rewritten with new config commands anyways. I have that on my backlog.

**Comment by dedmen** [comment]
Can you please explain? how is the last comment by KK conencted to this?

**Comment by shukari** [comment]
Also the str text thing only works for string and locations... sry my fault.
Issue can be closed.

**Comment by dedmen** [comment]
could also use `format` maybe. Dunno if that adds ""

**Comment by jonpas** [comment]
I am not going to rewrite that until you decide that and move whatever to C++. :P

**Comment by dedmen** [comment]
`str`ing should not be needed anymore and.. Whats your opinion on moving that to C++?

**Comment by jonpas** [comment]
I think it should all be done in C++, everything after the first `callExtension` that initializes it. No point not to that I see.

**Comment by dedmen** [comment]
Problem is Host doesn't have access to our SQF Wrappers. Meaning we need to write all that manually without access to wrappers

**Comment by jonpas** [comment]
Oh, in that case it might be better to leave it in SQF, just optimize it.

**Comment by dedmen** [comment]
Not only do we not have access to wrappers. We also don't have access to the pointers to engine functions that are used inside the wrappers. So IMO no way this will be put into host.

**Comment by jonpas** [comment]
Why close this though? That SQF could still be vastly improved using proper config commands.

**Comment by dedmen** [comment]
OP only talked about the `str` und un-str and call in boot.sqf. You can reopen it if you want to handle that here

**Comment by jonpas** [comment]
Ah I see, no worries, I will do it when I do it.
