### ISSUE TITLE
i can't find intercept_Core in wiki "Window Envionment Setup"

### ISSUE THREAD

**Issue by laskdjlaskdj12** [intercept/intercept#159]
when i build the project Hello_Intercept and make .pbo file by following wiki "Windows Environment Setup" the aram3 launcher says "Can't find addon Intercept_Core. ".  But i can't find any sign of Intercept_Core addition in wiki . Is there any help that i solve this problem?

**Comment by laskdjlaskdj12** [comment]
sorry about my writing. i was in upset that spending this all day.

**Comment by dedmen** [comment]
Also it is on the wiki.
**Download and Install the Latest Release of Intercept** -> **Installation** ->
>The host mod: This allows our code to be injected into the Arma 3. **This should be installed as an Arma 3 mod**

**Comment by laskdjlaskdj12** [comment]
oh... I missed that. tank you

**Comment by gsq7474741** [comment]
@dedmen 

arma3 can't find intercept_Core
Please give some info, thanks

btw,link is invalid
https://github.com/intercept/intercept/wiki/Windows-Environment-Setup-and-Sample-Client-Installation#installation

**Comment by dedmen** [comment]
https://github.com/intercept/intercept/wiki/Building-and-installing-Intercept-from-source

Seems like we don't describe anymore how to build the PBO's. Assuming you already know how to do that, if not then take the pbo from the latest release.
