### ISSUE TITLE
Plan for Intercept-Python

### ISSUE THREAD

**Issue by Tirpitz93** [intercept/intercept#168]
As the title says, is there a plan to embed a python interpreter with access to the RV engine?
I would be interested in contributing to the development for this if there is. Otherwise I would like to put it out there.

**Comment by dedmen** [comment]
https://github.com/intercept/intercept-python See Draft branch. Currently waiting on #110 to ease development.

**Comment by jonpas** [comment]
Also join [our Slack](http://slackin-intercept.idi-systems.com/) to discuss development with other developers!

**Comment by Tirpitz93** [comment]
Ah right there... exactly where it should be
