### ISSUE TITLE
Crash in new std::thread

### ISSUE THREAD

**Issue by Stolenko** [intercept/intercept#196]
Hello.
I have some problem with my application. I want to get a player's position several times a second.
If I do this in **intercept::on_frame**, then everything works fine:

```
void __cdecl intercept::on_frame() {
	object player = intercept::sqf::player();
	intercept::sqf::hint_silent(intercept::sqf::format({ "[%1]<br />", intercept::sqf::get_pos_asl(player) }));
}
```
but if I do this in a new thread:

```
std::thread test_thread;
std::atomic<bool> stop_thread;

void test_thread_func() {
	object player = intercept::sqf::player();
	while (!stop_thread) {
		intercept::sqf::hint_silent(intercept::sqf::format({ "[%1]<br />",  intercept::sqf::get_pos_asl(player) }));
		std::this_thread::sleep_for(50ms);
	}
}
void __cdecl intercept::post_init() {
	stop_thread = false;
	test_thread = std::thread(&test_thread_func);
}
```

then after a while (up to 20 seconds) the game crashes.

What am I doing wrong? Why is the game crashing?

**Comment by dedmen** [comment]
https://github.com/intercept/intercept/wiki/Threading-Models
Arma is single threaded. You can't just script in a seperate thread.
You are missing the invoker lock.
