### ISSUE TITLE
error iterating over all_players() 

### ISSUE THREAD

**Issue by darthun** [intercept/intercept#205]
First time reporting a bug here. I'm using the example template and running code in post_init();

Basically, you can't count the iterations over the vector returned by calling all_players() without the game crashing.

I understand that all_players() returns players + headless clients,  but the size is 1 when explicitly called in my code.

Reproduction procedure : 

```
auto all_players = sqf::all_players();
std::vector<intercept::types::object>::iterator it;
it = sqf::all_players().begin();
all_players.size() // size returns 1 when tested in the arma editor.
int i = 1;
while( it != all_players.end())
{
		{
			client::invoker_lock thread_lock;
			sqf::system_chat("why do i display 5 times ?");
			it++;
			// i++; this line crashes the program.
		} 
}
```
Same results without the thread lock.

**Comment by dedmen** [comment]
You can't use Intercept if you don't know c++ basics.
`it = sqf::all_players().begin();`
`sqf::all_players()` returns a temporary.
`.begin()` grabs a iterator to the temporary.
temporary isn't needed anymore so it's deleted now.
`it =` you assign a invalid iterator to `it`
`it++;` you cannot increment a invalid iterator.

Also please use modern C++ and not c++98.

```
auto all_players = sqf::all_players();
all_players.size() // size returns 1 when tested in the arma editor.
for (auto& it: all_players)
    sqf::system_chat("why do i display 5 times ?");
```
Also why are you putting the invoker_lock in there? that's either not needed there or you are doing it wrong. Well. In both cases you are doing it wrong.
