### ISSUE TITLE
Add Wiki section on how to load/unload Plugins dynamically

### ISSUE THREAD

**Issue by JamieGoodson** [intercept/intercept#235]
Small suggestion for the wiki:

https://github.com/jamiegdsn/intercept/wiki/Writing-Plugins/_compare/818f0ceb477d376ba72e6408486435da9e3a0a40

Sorry if there's a better way to do this. AFAIK there isn't a way to create pull requests for Wiki changes.

**Comment by Leopard20** [comment]
Added
