### ISSUE TITLE
[WIKI] Wrong artifacts URL in "Getting Started"

### ISSUE THREAD

**Issue by bastilimbach** [intercept/intercept#261]
Hi 👋 ,

I noticed that you switched from AppVeyor to GitHub actions. However, in the Wiki, you still point to the artifacts on AppVeyor in the "Download the latest release and Install it" section: https://github.com/intercept/intercept/wiki/Getting-Started#download-the-latest-release-and-install-it

This link downloads an empty folder. It should be changed to point to the GitHub Actions artifacts instead.
Unfortunately, I cannot create a PR for wiki changes. Therefore only this issue.

**Comment by Leopard20** [comment]
Hi. Thanks for reporting the issue. 
I updated the link to point to GitHub Actions.
