### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by StokesMagee** [intercept/intercept#283]
Unable to compile due to sqf_string_const_ref and sqf_string 

https://github.com/intercept/intercept/blob/4c0f308852fc14753db937669ce340d59f99ab71/src/client/headers/client/sqf/world.hpp#L182

https://github.com/intercept/intercept/blob/4c0f308852fc14753db937669ce340d59f99ab71/src/client/headers/client/sqf/world.hpp#L220

**Comment by StokesMagee** [comment]
error C2668: 'intercept::types::r_string::r_string': ambiguous call to overloaded function

**Comment by Leopard20** [comment]
What compiler?

**Comment by StokesMagee** [comment]
I've tried MSVC 2017, 2019, and 2022, with v141 and all have the same issue as above.

**Comment by Leopard20** [comment]
Have you checked `Enable engine types` in CMake options?

**Comment by Leopard20** [comment]
Can you try the PR to see if it actually fixes your issue?

**Comment by StokesMagee** [comment]
No, that did not resolve the issue, However, I attempted to fix it and the only result I came up with was changing 
"sqf_string_const_ref rainDropTexture_, " to "sqf_string rainDropTexture_,"

**Comment by StokesMagee** [comment]
> No, that did not resolve the issue, However, I attempted to fix it and the only result I came up with was changing "sqf_string_const_ref rainDropTexture_, " to "sqf_string rainDropTexture_,"
> 
> Yes I am using engine types, all options besides debug_loader are enabled.

This seems to work without issues. but I'm not using any relation to this, so unsure if it's a proper solution.

**Comment by Leopard20** [comment]
How are you using the command? I assume you just supply a literal string right?

**Comment by Leopard20** [comment]
Also is the new error message the same?

**Comment by Leopard20** [comment]
Should be fixed now. If you still can't compile let me know.
