### ISSUE TITLE
Incorrect implementation of some autogenerated wrappers

### ISSUE THREAD

**Issue by Verox-** [intercept/intercept#29]
Some of the autogenerated wrappers for the binary functions have inverted parameters, but not all.
Ideally we could just regenerate these wrappers, it'd be the fastest and easiest method of fixing this problem, the other way is doing it manually. (dibs not me)

**Comment by Glowbal** [comment]
I fixed this once, it took ~10 minutes. I will redo it.

**Comment by jonpas** [comment]
Some fixed in #50

**Comment by NouberNou** [comment]
Is this done? I think it is?

**Comment by jonpas** [comment]
There probably still are a few wrong, but we fix them as we see them.

**Comment by NouberNou** [comment]
Cool, closing then.

**Comment by jonpas** [comment]
Remove WIP label as well. :)
