### ISSUE TITLE
undefined reference to `vtable for intercept::types::game_value'

### ISSUE THREAD

**Issue by skyracer2012** [intercept/intercept#296]
Hey,
I am trying to compile a arma extension with intercept using mingw.

I plan on using intercept via a library and added the include folder as seen in [Intercept 0.12.0.863](https://github.com/intercept/intercept/releases/tag/0.12.0).

When compiling I however get the follwing error:
`/usr/bin/x86_64-w64-mingw32-ld: CMakeFiles/ExtensionTest.dir/main.cpp.o:main.cpp:(.rdata$.refptr._ZTVN9intercept5types10game_valueE[.refptr._ZTVN9intercept5types10game_valueE]+0x0): undefined reference to `vtable for intercept::types::game_value'`

I did search and think the issue might be in the intercept::types::game_value constructor. I also removed the calls for __set_vtable from the constructor and return early. However I wasn't able to find any information on how to actually fix this issue.

EDIT:
Using the current main source code I also get this error which (might) be in common with the issue above?
`/usr/bin/x86_64-w64-mingw32-ld: CMakeFiles/ExtensionTest.dir/main.cpp.o:main.cpp:(.rdata$.refptr._ZN9intercept5types10game_value10__vptr_defE[.refptr._ZN9intercept5types10game_value10__vptr_defE]+0x0): undefined reference to `intercept::types::game_value::__vptr_def'
`
which is pretty wierd to me because __vptr_def is defined directly above the constructor.

**Comment by dedmen** [comment]
> using mingw.

mingw is not supported.
We only support Visual Studio on windows, and GCC on linux.
That will be your issue.
