### ISSUE TITLE
Doesn't work on the newest ArmA version

### ISSUE THREAD

**Issue by FlickoArtz** [intercept/intercept#303]
[
![Screenshot 2024-10-20 225118](https://github.com/user-attachments/assets/51f3e848-738f-4310-8dc4-8e6e5c7cea79)
](url)

**Comment by Leopard20** [comment]
Where did you get it from? The latest master should work.

**Comment by FlickoArtz** [comment]
My bad i hit my caps button. 
I got it from something called Finistar, but he said he was waiting for an update to intercept.

**Comment by Leopard20** [comment]
@FlickoArtz has the issue been resolved?
